---
- name: Build Icecast
  include_tasks: icecast.yml

- name: Build Liquidsoap (Legacy Ubuntu Versions)
  include_tasks: liquidsoap_legacy.yml
  when:
    - ansible_distribution_release == 'xenial' or ansible_distribution_release == 'bionic'

- name: Install Liquidsoap (Focal)
  include_tasks: liquidsoap.yml
  when:
    - ansible_distribution_release == 'focal'

- name : Add Audiowaveform PPA
  apt_repository :
    repo : "ppa:chris-needham/ppa"
    update_cache : yes

- name : Install Audiowaveform
  apt :
    name : audiowaveform
    state : latest
    install_recommends : no

- name : Install Flac
  apt :
    name : flac
    state : latest
    install_recommends : no

- name : Install Vorbis-Tools
  apt :
    name : vorbis-tools
    state : latest
    install_recommends : no
