---
- name: Add SFTPGo PPA repository
  apt_repository:
    repo: "ppa:sftpgo/sftpgo"
    update_cache: true

- name: Install SFTPGo
  apt:
    name: "sftpgo"
    state: present

- name: Configure SFTPGo
  template:
    src: sftpgo.json.j2
    dest: "/etc/sftpgo/sftpgo.json"
    force: true
    mode: 0644
