github :
  prebuilds :
    addCheck : false

vscode :
  extensions :
    - bmewburn.vscode-intelephense-client
    - editorconfig.editorconfig

tasks :
  - name : Docker Build
    init : |
      make install-gitpod
      gp sync-done docker-build
    command : |
      make up
      make bash

  - name : Static Service
    openMode : split-right
    init : |
      gp sync-await docker-build
      make frontend-build
    command : |
      make frontend-bash
