github :
  prebuilds :
    addCheck : false

tasks :
  - name : Docker Build
    init : |
      yes '' | bash docker.sh install-dev
      gp sync-done docker-build
    command : |
      make up
      make bash

  - name : Static Service
    openMode : split-right
    command :
      gp sync-await docker-build
      make frontend-bash
