services:
  frontend:
    container_name: azuracast_frontend
    build:
      context: ./frontend
    user: "${AZURACAST_PUID:-1000}:${AZURACAST_PGID:-1000}"
    volumes:
      - $PWD/frontend:/data/frontend
      - $PWD/translations:/data/translations
      - $PWD/web/static:/data/web/static
      - frontend_node_modules:/data/frontend/node_modules

volumes:
  frontend_node_modules: { }
