services:
  installer:
    container_name: azuracast_installer
    image: 'azuracast.docker.scarf.sh/azuracast/azuracast:${AZURACAST_VERSION:-latest}'
    volumes:
      - './:/installer'
    restart: 'no'
    entrypoint: docker_installer
    command: install
