version : '2.2'

services :
  web :
    image : azuracast_cli:latest
    environment :
      APPLICATION_ENV : 'testing'
    build :
      context : ./util/docker/testing
      cache_from :
        - azuracast/azuracast_web_v2:latest
    volumes :
      - .:/var/azuracast/www
