version: '2.2'

services :
  web :
    build :
      context : .
      target : testing
      cache_from :
        - azuracast/azuracast_web_v2:latest
    environment :
      APPLICATION_ENV : 'testing'
    volumes :
      - .:/var/azuracast/www
