---
- name: Install supervisord from repo
  apt:
    name: supervisor

- name: Change supervisord configuration
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    force: true
    mode: 0644

- name: Remove old core supervisord configurations
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/supervisor/conf.d/*.conf"
  ignore_errors: true
