---
- name: Install supervisord from repo
  apt:
    name: supervisor

- name: Change supervisord configuration
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    force: true
    mode: 0644

- name: Remove old core supervisord configuration
  file:
    path: /etc/supervisor/conf.d/core.conf
    state: absent
