---
- name: Update MariaDB Dependencies
  shell: >-
    curl -sSL https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
    | bash -s -- --mariadb-server-version="mariadb-10.5"

- name: Remove old MariaDB conf files
  file:
    path: /etc/apt/sources.list.d/mariadb.list.old*
    state: absent
  ignore_errors: true

- name: Install MariaDB
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - mariadb-server
      - mariadb-client

- name: Install MariaDB DB conf
  template:
    src: my.cnf.j2
    dest: /etc/mysql/conf.d/db.cnf
    force: true
    mode: 0644
