---
- name: Add Redis PPA repository
  apt_repository:
    repo: "ppa:chris-lea/redis-server"
    update_cache: true

- name: Install Redis
  apt:
    name: redis-server

- name: Install Redis Supervisord conf
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/redis.conf
    force: true
    mode: 0644

- name: Enable and restart all core services
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: true
  with_items:
    - "redis-server"
    - "redis"
