---
- name: Add Redis PPA repository
  apt_repository:
    repo: "ppa:chris-lea/redis-server"
    update_cache: true

- name: Install Redis
  apt:
    name: redis-server

- name: Install Redis Conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    force: true
    owner: "redis"
    mode: 0644

- name: Create Redis run dir
  file:
    path: /run/redis
    owner: "redis"
    state: directory
